server:
  port: 9001

spring:
  application:
    name: PORTFOLIO-SERVICE
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka