server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: STOCK-SERVICE
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock/**
        - id: PORTFOLIO-SERVICE
          uri: lb://PORTFOLIO-SERVICE
          predicates:
            - Path=/portfolio/**
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: BUDGET-SERVICE
          uri: lb://BUDGET-SERVICE
          predicates:
            - Path=/api/**
        - id: ESG-SERVICE
          uri: lb://ESG-SERVICE
          predicates:
            - Path=/esg/**
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

